version: '3.8'
services:
  cms:
    build: .
    ports:
      - "8085:80"
    networks:
      - event-net
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event management
    networks:
      - event-net

networks:
  event-net:
    driver: bridge
